devices:
  capture:
    channels: 2
    device: hw:Loopback,1
    format: S24LE3
    type: Alsa
  chunksize: 16384
  playback:
    channels: 2
    device: hw:v15,0
    format: S24LE3
    type: Alsa
  samplerate: 96000
  silence_threshold: -60
  silence_timeout: 3.0
filters:
  AKGK702_oratory1990_14062021_band01:
    parameters:
      freq: 24
      gain: 5.0
      q: 0.71
      type: Lowshelf
    type: Biquad
  AKGK702_oratory1990_14062021_band02:
    parameters:
      freq: 105
      gain: 5.5
      q: 0.71
      type: Lowshelf
    type: Biquad
  AKGK702_oratory1990_14062021_band03:
    parameters:
      freq: 200
      gain: -2.5
      q: 0.5
      type: Peaking
    type: Biquad
  AKGK702_oratory1990_14062021_band04:
    parameters:
      freq: 740
      gain: 2.4
      q: 1.4
      type: Peaking
    type: Biquad
  AKGK702_oratory1990_14062021_band05:
    parameters:
      freq: 1000
      gain: -1.2
      q: 3.5
      type: Peaking
    type: Biquad
  AKGK702_oratory1990_14062021_band06:
    parameters:
      freq: 2280
      gain: -5.3
      q: 1.9
      type: Peaking
    type: Biquad
  AKGK702_oratory1990_14062021_band07:
    parameters:
      freq: 2650
      gain: -0.6
      q: 5.0
      type: Peaking
    type: Biquad
  AKGK702_oratory1990_14062021_band08:
    parameters:
      freq: 3500
      gain: 3.0
      q: 1.4
      type: Peaking
    type: Biquad
  AKGK702_oratory1990_14062021_band09:
    parameters:
      freq: 5500
      gain: -5.0
      q: 3.5
      type: Peaking
    type: Biquad
  AKGK702_oratory1990_14062021_band10:
    parameters:
      freq: 12000
      gain: -1.0
      q: 0.71
      type: Highshelf
    type: Biquad
  AKGK702_oratory1990_14062021_gain:
    parameters:
      gain: -10.4
    type: Gain
  hp700:
    parameters:
      freq: 700
      gain: 2
      slope: 6
      type: Highshelf
    type: Biquad
  lp700:
    parameters:
      freq: 700
      type: LowpassFO
    type: Biquad
mixers:
  2to4:
    channels:
      in: 2
      out: 4
    mapping:
    - dest: 0
      mute: false
      sources:
      - channel: 0
        gain: -2
        inverted: false
        mute: false
    - dest: 1
      mute: false
      sources:
      - channel: 0
        gain: -5
        inverted: false
        mute: false
    - dest: 2
      mute: false
      sources:
      - channel: 1
        gain: -5
        inverted: false
        mute: false
    - dest: 3
      mute: false
      sources:
      - channel: 1
        gain: -2
        inverted: false
        mute: false
  4to2:
    channels:
      in: 4
      out: 2
    mapping:
    - dest: 0
      mute: false
      sources:
      - channel: 0
        gain: -2
        inverted: false
        mute: false
      - channel: 2
        gain: -2
        inverted: false
        mute: false
    - dest: 1
      mute: false
      sources:
      - channel: 1
        gain: -2
        inverted: false
        mute: false
      - channel: 3
        gain: -2
        inverted: false
        mute: false
pipeline:
- name: 2to4
  type: Mixer
- channels:
  - 0
  names:
  - hp700
  type: Filter
- channels:
  - 1
  names:
  - lp700
  type: Filter
- channels:
  - 2
  names:
  - lp700
  type: Filter
- channels:
  - 3
  names:
  - hp700
  type: Filter
- name: 4to2
  type: Mixer
- channels:
  - 0
  names:
  - AKGK702_oratory1990_14062021_gain
  - AKGK702_oratory1990_14062021_band01
  - AKGK702_oratory1990_14062021_band02
  - AKGK702_oratory1990_14062021_band03
  - AKGK702_oratory1990_14062021_band04
  - AKGK702_oratory1990_14062021_band05
  - AKGK702_oratory1990_14062021_band06
  - AKGK702_oratory1990_14062021_band07
  - AKGK702_oratory1990_14062021_band08
  - AKGK702_oratory1990_14062021_band09
  - AKGK702_oratory1990_14062021_band10
  type: Filter
- channels:
  - 1
  names:
  - AKGK702_oratory1990_14062021_gain
  - AKGK702_oratory1990_14062021_band01
  - AKGK702_oratory1990_14062021_band02
  - AKGK702_oratory1990_14062021_band03
  - AKGK702_oratory1990_14062021_band04
  - AKGK702_oratory1990_14062021_band05
  - AKGK702_oratory1990_14062021_band06
  - AKGK702_oratory1990_14062021_band07
  - AKGK702_oratory1990_14062021_band08
  - AKGK702_oratory1990_14062021_band09
  - AKGK702_oratory1990_14062021_band10
  type: Filter
