devices:
  capture:
    channels: 2
    device: hw:Loopback,1
    format: S24LE3
    type: Alsa
  chunksize: 16384
  playback:
    channels: 2
    device: hw:v15,0
    format: S24LE3
    type: Alsa
  samplerate: 96000
  silence_threshold: -60
  silence_timeout: 3.0
filters:
  ATHM50X_oratory1990_28042021_band01:
    parameters:
      freq: 40
      gain: -3.1
      q: 0.6
      type: Peaking
    type: Biquad
  ATHM50X_oratory1990_28042021_band02:
    parameters:
      freq: 105
      gain: 5.5
      q: 0.71
      type: Lowshelf
    type: Biquad
  ATHM50X_oratory1990_28042021_band03:
    parameters:
      freq: 165
      gain: -4.6
      q: 0.9
      type: Peaking
    type: Biquad
  ATHM50X_oratory1990_28042021_band04:
    parameters:
      freq: 315
      gain: 5.7
      q: 1.4
      type: Peaking
    type: Biquad
  ATHM50X_oratory1990_28042021_band05:
    parameters:
      freq: 2000
      gain: 3.0
      q: 0.71
      type: Highshelf
    type: Biquad
  ATHM50X_oratory1990_28042021_band06:
    parameters:
      freq: 2800
      gain: -5.5
      q: 1.7
      type: Peaking
    type: Biquad
  ATHM50X_oratory1990_28042021_band07:
    parameters:
      freq: 4340
      gain: -5.6
      q: 4.5
      type: Peaking
    type: Biquad
  ATHM50X_oratory1990_28042021_band08:
    parameters:
      freq: 7050
      gain: -3.6
      q: 6.0
      type: Peaking
    type: Biquad
  ATHM50X_oratory1990_28042021_band09:
    parameters:
      freq: 8000
      gain: -5.0
      q: 5.0
      type: Peaking
    type: Biquad
  ATHM50X_oratory1990_28042021_band10:
    parameters:
      freq: 11000
      gain: -11.0
      q: 0.71
      type: Highshelf
    type: Biquad
  ATHM50X_oratory1990_28042021_gain:
    parameters:
      gain: -5
    type: Gain
pipeline:
- channels:
  - 0
  names:
  - ATHM50X_oratory1990_28042021_gain
  - ATHM50X_oratory1990_28042021_band01
  - ATHM50X_oratory1990_28042021_band02
  - ATHM50X_oratory1990_28042021_band03
  - ATHM50X_oratory1990_28042021_band04
  - ATHM50X_oratory1990_28042021_band05
  - ATHM50X_oratory1990_28042021_band06
  - ATHM50X_oratory1990_28042021_band07
  - ATHM50X_oratory1990_28042021_band08
  - ATHM50X_oratory1990_28042021_band09
  - ATHM50X_oratory1990_28042021_band10
  type: Filter
- channels:
  - 1
  names:
  - ATHM50X_oratory1990_28042021_gain
  - ATHM50X_oratory1990_28042021_band01
  - ATHM50X_oratory1990_28042021_band02
  - ATHM50X_oratory1990_28042021_band03
  - ATHM50X_oratory1990_28042021_band04
  - ATHM50X_oratory1990_28042021_band05
  - ATHM50X_oratory1990_28042021_band06
  - ATHM50X_oratory1990_28042021_band07
  - ATHM50X_oratory1990_28042021_band08
  - ATHM50X_oratory1990_28042021_band09
  - ATHM50X_oratory1990_28042021_band10
  type: Filter
