---
# CamillaDSP setup file:
# EQ setting for Sennheiser  HD560S by Oratory1990 from
# 06.01.22 v2.9 Sennheiser HD560S:
# https://www.reddit.com/r/oratory1990/wiki/index/list_of_presets
#
# Also see: 
# https://github.com/scripple/alsa_cdsp
# https://www.diyaudio.com/forums/pc-based/349818-camilladsp-cross-platform-iir-fir-engine-crossovers-correction-etc-198.html
# 

devices:
  samplerate: 96000
  chunksize: 16384
  silence_threshold: -60
  silence_timeout: 3.0
  capture:
    type: Alsa
    channels: 2
    device: "hw:Loopback,1"
    format: S24LE3
  playback:
    type: Alsa
    channels: 2
    device: "hw:v15,0"
    format: S24LE3

# devices:
#   samplerate: $samplerate$
#   chunksize: 16384
#   queuelimit: 1
#   capture:
#     type: File
#     channels: $channels$
#     filename: "/dev/stdin"
#     format: $format$
#   playback:
#     type: ALSA
#     channels: $channels$
#     device: "hw:0"
#     format: S32LE

filters:
  SENNHD560S_oratory1990_06012022_gain:
    type: Gain
    parameters:
      gain: -5.4

  SENNHD560S_oratory1990_06012022_band01:
    type: Biquad
    parameters:
      type: Peaking
      freq: 53
      gain: -2.3
      q: 1.0 

  SENNHD560S_oratory1990_06012022_band02:
    type: Biquad
    parameters:
      type: Lowshelf
      freq: 105
      gain: 5.5
      q: 0.71
      
  SENNHD560S_oratory1990_06012022_band03:
    type: Biquad
    parameters:
      type: Peaking
      freq: 140
      gain: -1.8
      q: 0.7
      
  SENNHD560S_oratory1990_06012022_band04:
    type: Biquad
    parameters:
      type: Peaking
      freq: 1350
      gain: -3.2
      q: 1.5
      
  SENNHD560S_oratory1990_06012022_band05:
    type: Biquad
    parameters:
      type: Peaking
      freq: 1830
      gain: 2.3
      q: 1.3
      
  SENNHD560S_oratory1990_06012022_band06:
    type: Biquad
    parameters:
      type: Peaking
      freq: 3230
      gain: -1.3
      q: 4.0

  SENNHD560S_oratory1990_06012022_band07:
    type: Biquad
    parameters:
      type: Peaking
      freq: 4420
      gain: -3.1
      q: 4.5
      
  SENNHD560S_oratory1990_06012022_band08:
    type: Biquad
    parameters:
      type: Peaking
      freq: 5600
      gain: -4.1
      q: 2.5

  SENNHD560S_oratory1990_06012022_band09:
    type: Biquad
    parameters:
      type: Peaking
      freq: 7000
      gain: 2.5
      q: 1.2
      
  SENNHD560S_oratory1990_06012022_band10: 
    type: Biquad
    parameters:
      type: Highshelf 
      freq: 10000
      gain: -1.0
      q: 0.71 

# Filters for Crossfeed
  hp700:
    type: Biquad
    parameters:
      freq: 700
      gain: 2
      slope: 6
      type: Highshelf
      
  lp700:
    type: Biquad
    parameters:
      freq: 700
      type: LowpassFO
      
# Mixers for Crossfeed     
mixers:
  2to4:
    channels:
      in: 2
      out: 4
    mapping:
    - dest: 0
      mute: false
      sources:
      - channel: 0
        gain: -2
        inverted: false
        mute: false
    - dest: 1
      mute: false
      sources:
      - channel: 0
        gain: -5
        inverted: false
        mute: false
    - dest: 2
      mute: false
      sources:
      - channel: 1
        gain: -5
        inverted: false
        mute: false
    - dest: 3
      mute: false
      sources:
      - channel: 1
        gain: -2
        inverted: false
        mute: false
  4to2:
    channels:
      in: 4
      out: 2
    mapping:
    - dest: 0
      mute: false
      sources:
      - channel: 0
        gain: -2
        inverted: false
        mute: false
      - channel: 2
        gain: -2
        inverted: false
        mute: false
    - dest: 1
      mute: false
      sources:
      - channel: 1
        gain: -2
        inverted: false
        mute: false
      - channel: 3
        gain: -2
        inverted: false
        mute: false  

pipeline:

# Crossfeed

  - name: 2to4
    type: Mixer
  
  - channel: 0
    names:
    - hp700
    type: Filter
    
  - channel: 1
    names:
    - lp700
    type: Filter
    
  - channel: 2
    names:
    - lp700
    type: Filter
    
  - channel: 3
    names:
    - hp700
    type: Filter
    
  - name: 4to2
    type: Mixer


# Headphone EQ

  - type: Filter
    channel: 0
    names:
      - SENNHD560S_oratory1990_06012022_gain
      - SENNHD560S_oratory1990_06012022_band01
      - SENNHD560S_oratory1990_06012022_band02
      - SENNHD560S_oratory1990_06012022_band03
      - SENNHD560S_oratory1990_06012022_band04
      - SENNHD560S_oratory1990_06012022_band05
      - SENNHD560S_oratory1990_06012022_band06
      - SENNHD560S_oratory1990_06012022_band07
      - SENNHD560S_oratory1990_06012022_band08
      - SENNHD560S_oratory1990_06012022_band09
      - SENNHD560S_oratory1990_06012022_band10

  - type: Filter
    channel: 1
    names:
      - SENNHD560S_oratory1990_06012022_gain
      - SENNHD560S_oratory1990_06012022_band01
      - SENNHD560S_oratory1990_06012022_band02
      - SENNHD560S_oratory1990_06012022_band03
      - SENNHD560S_oratory1990_06012022_band04
      - SENNHD560S_oratory1990_06012022_band05
      - SENNHD560S_oratory1990_06012022_band06
      - SENNHD560S_oratory1990_06012022_band07
      - SENNHD560S_oratory1990_06012022_band08
      - SENNHD560S_oratory1990_06012022_band09
      - SENNHD560S_oratory1990_06012022_band10
      